$(document).ready(function(){if($("[id$='hidAlphabet']").val()!=""){$("a[href*='?startwith="+$("[id$='hidAlphabet']").val()+"'").addClass("active");}
$("[id$='aSearch']").click(function(){if($(".page-home").length===0)
window.location=$(location).attr("pathname")+"?searchTxt="+$("[id$='txtWord']").val();else
window.location="/"+$("#hidCultureAlias").val()+"/search-results?searchtext="+$("[id$='txtWord']").val();});$("[id$='txtWord']").on('keyup',function(e){if(e.keyCode==13)
if($(".page-home").length===0)
window.location=$(location).attr("pathname")+"?searchTxt="+$("[id$='txtWord']").val();else
window.location="/"+$("#hidCultureAlias").val()+"/search-results?searchtext="+$("[id$='txtWord']").val();});$("[id$='txtSearchQuery']").on('keyup',function(e){if(e.keyCode==13)
window.location="/"+$("#hidCultureAlias").val()+"/search-results?searchtext="+$("[id$='txtSearchQuery']").val();});$("[id$='btnSearchText']").click(function(e){window.location="/"+$("#hidCultureAlias").val()+"/search-results?searchtext="+$("[id$='txtSearchQuery']").val();});CheckClass();});function CheckClass(){$(window).scroll(function(){if(document.documentElement.scrollTop>448.888916015625&&$("[id$='float']").length>0){$("[id$='float']").addClass("hitTop");$(".floatItem--conditions.d-none").addClass("d-sm-flex");$(".floatItem--conditions.d-block").addClass("d-flex");}else if($("[id$='float']").length>0){$("[id$='float']").removeClass("hitTop");$(".floatItem--conditions.d-none").removeClass("d-sm-flex");$(".floatItem--conditions.d-block").removeClass("d-flex");}});}
function setCookie(cname,cvalue,exdays){var d=new Date();d.setTime(d.getTime()+(exdays*24*60*60*1000));var expires="expires="+d.toUTCString();document.cookie=cname+"="+cvalue+";"+expires+";path=/;Secure";}
function getCookie(cname){var name=cname+"=";var ca=document.cookie.split(';');for(var i=0;i<ca.length;i++){var c=ca[i];while(c.charAt(0)==' '){c=c.substring(1);}
if(c.indexOf(name)==0){return c.substring(name.length,c.length);}}
return "";}
function blueKaiCartEvent(skuname){$("body").append("<img src='https://stags.bluekai.com/site/85770?phint=cart_packages%3D"+$('<div/>').text(skuname).html()+"&phint=event%3Dadd_to_cart_button'/>");}
$(document).ready(function(){$(window).scroll(function(){if($(window).scrollTop()>300){$('#button-gototop').addClass('show');}else{$('#button-gototop').removeClass('show');}});$('#button-gototop').on('click',function(e){e.preventDefault();$('html, body').animate({scrollTop:0},'300');});});var counterLoadMore=[];function LoadmoreToggleFilter(obj,chkId,name){var mainId=LoadmoreGetMainID(obj.id);var hiddenCountTweetID=LoadmoreGetID(obj.id,'hdCountTweet');counterLoadMore[mainId]=0;$('#'+hiddenCountTweetID).val('0');$(obj).toggleClass('filter__item--selected');var checkBoxes=$('#'+chkId);var allCheckBox=$('[id*="chkFilterDropdown"][type="checkbox"]');allCheckBox.attr('checked',false);checkBoxes.attr('checked',!checkBoxes.attr('checked'));$('#dropdownMenuButton'+name).text(obj.text);return false;}
function LoadmoreToggleTab(obj,chkId){var mainId=LoadmoreGetMainID(obj.id);var hiddenCountTweetID=LoadmoreGetID(obj.id,'hdCountTweet');counterLoadMore[mainId]=0;$('#'+hiddenCountTweetID).val('0');$(obj).toggleClass('filter__item--selected');var checkBoxes=$('#'+chkId);var allCheckBox=$('input[id*="chkFilterTab"][type="checkbox"]');allCheckBox.attr('checked',false);checkBoxes.attr('checked',!checkBoxes.attr('checked'));return false;}
function LoadmoreSelectFilter(obj){var mainId=LoadmoreGetMainID(obj.id);var submitBtnId=LoadmoreGetID(obj.id,'btnSubmit');counterLoadMore[mainId]=0;$('#'+submitBtnId).click();return false;}
function LoadmoreSeeLess(obj){var mainId=LoadmoreGetMainID(obj.id);var hiddenCountTweetID=LoadmoreGetID(obj.id,'hdCountTweet');counterLoadMore[mainId]=0;$('#'+hiddenCountTweetID).val('0');$(obj).addClass("disabled");$(obj).val($(obj).attr("data-loading-text"));return true;}
function LoadmoreLoadmore(obj){$(obj).addClass("disabled");$(obj).val($(obj).attr("data-loading-text"));return true;}
function LoadmoreGetID(sourceId,newElement){var element=sourceId.split("_").pop();return sourceId.replace('_'+element,'_'+newElement);}
function LoadmoreGetMainID(sourceId){var element=sourceId.split("_").pop();return sourceId.replace('_'+element,'');}
function LoadmoreSchrollLoad(source){var mainId=LoadmoreGetMainID(source);var hiddenSchrollLoadPaddingTopID=LoadmoreGetID(source,'hdSchrollLoadPaddingTop');var hiddenCountTweetID=LoadmoreGetID(source,'hdCountTweet');var hiddenTotalItemID=LoadmoreGetID(source,'hdTotalItem');var lbLoadmoreText=LoadmoreGetID(source,'lbLoadmoreText');var submitBtnId=LoadmoreGetID(source,'btnSubmit');var lastItem=$("#"+mainId+"_updPanel"+" div.item-load").last();if(typeof lastItem!='undefined'&&lastItem.length>0){if(($(window).scrollTop()+$(window).height())>=($("#"+lbLoadmoreText).offset().top)){if(counterLoadMore[mainId]==(parseInt($('#'+hiddenCountTweetID).val())-1)&&$("div.item-load").length<parseInt($('#'+hiddenTotalItemID).val())){$('#'+submitBtnId).click();$("#"+lbLoadmoreText).removeClass("d-none");counterLoadMore[mainId]++;}else if($("#"+mainId+"_updPanel"+" div.item-load").length>=parseInt($('#'+hiddenTotalItemID).val())){$("#"+lbLoadmoreText).addClass("d-none");}}}}
$(document).ready(function(){$('div[id*=_updPanel] input[id*="_btnSubmit"][class*=filter__submit]').each(function(){var mainId=LoadmoreGetMainID(this.id);counterLoadMore[mainId]=0;});$(window).scroll(function(){$('div[id*=_updPanel] input[id*="_btnSubmit"][class*=filter__submit]').each(function(){var mainId=LoadmoreGetMainID(this.id);var hiddenIsUseLoadMoreID=LoadmoreGetID(mainId+"_t",'hdIsUseLoadMore');if($("#"+hiddenIsUseLoadMoreID).val()=="schroll"){LoadmoreSchrollLoad(hiddenIsUseLoadMoreID);}});});});